
[workspace]
switch = "Command+{N}"
moveTo = "Shift+Command+{N}"
moveColumnTo = "Unassigned"
backAndForth = "Unassigned"
next = "Unassigned"
previous = "Unassigned"

[focus]
column = "Control+Option+Command+{N}"
windowInColumn = "Unassigned"
left = "Command+H"
down = "Command+J"
up = "Command+K"
right = "Command+L"
previous = "Unassigned"
downOrLeft = "Unassigned"
upOrRight = "Unassigned"
windowTop = "Unassigned"
windowBottom = "Unassigned"
windowDownOrTop = "Unassigned"
windowUpOrBottom = "Unassigned"
windowOrWorkspaceDown = "Unassigned"
windowOrWorkspaceUp = "Unassigned"
columnFirst = "Command+Home"
columnLast = "Command+End"
monitorNext = "Command+P"
monitorPrevious = "Unassigned"
monitorLast = "Unassigned"

[move]
columnToIndex = "Unassigned"
left = "Unassigned"
down = "Shift+Command+J"
up = "Shift+Command+K"
right = "Unassigned"
windowDown = "Unassigned"
windowUp = "Unassigned"
windowDownOrToWorkspaceDown = "Unassigned"
windowUpOrToWorkspaceUp = "Unassigned"
windowToWorkspaceUp = "Unassigned"
windowToWorkspaceDown = "Unassigned"
columnToWorkspaceUp = "Unassigned"
columnToWorkspaceDown = "Unassigned"
columnLeft = "Shift+Command+H"
columnRight = "Shift+Command+L"
columnToFirst = "Unassigned"
columnToLast = "Unassigned"
consumeOrExpelLeft = "Unassigned"
consumeOrExpelRight = "Unassigned"
consumeIntoColumn = "Command+Comma"
expelFromColumn = "Command+Period"

[layout]
toggleFullscreen = "Command+F"
toggleNativeFullscreen = "Shift+Command+F"
toggleColumnTabbed = "Unassigned"
toggleColumnFullWidth = "Unassigned"
expandColumnToAvailable = "Control+Option+Command+F"
cycleColumnWidthForward = "Command+R"
cycleColumnWidthBackward = "Unassigned"
cycleWindowWidthForward = "Unassigned"
cycleWindowWidthBackward = "Unassigned"
cycleWindowHeightForward = "Unassigned"
cycleWindowHeightBackward = "Unassigned"
decreaseColumnWidth = "Command+Minus"
increaseColumnWidth = "Command+Equal"
decreaseWindowWidth = "Unassigned"
increaseWindowWidth = "Unassigned"
decreaseWindowHeight = "Option+Shift+Command+Minus"
increaseWindowHeight = "Option+Shift+Command+Equal"
resetWindowHeight = "Control+Option+Command+R"
balanceSizes = "Shift+Command+B"
centerColumn = "Shift+Command+C"
centerVisibleColumns = "Unassigned"
toggleFocusedFloating = "Shift+Command+V"
assignScratchpad = "Shift+Command+Space"
toggleScratchpad = "Command+Space"
raiseAllFloating = "Unassigned"
rescueOffscreen = "Command+F12"

[ui]
commandPalette = "Shift+Command+M"
menuAnywhere = "Unassigned"
toggleOverview = "Command+O"
toggleWorkspaceBar = "Unassigned"
