
[workspace]
switch = "Command+{N}"
moveTo = "Shift+Command+{N}"
moveColumnTo = "Unassigned"
focusAnywhere = "Unassigned"
backAndForth = "Unassigned"
next = "Unassigned"
previous = "Unassigned"
swapWithMonitorLeft = "Unassigned"
swapWithMonitorRight = "Unassigned"
swapWithMonitorUp = "Unassigned"
swapWithMonitorDown = "Unassigned"

[focus]
column = "Control+Option+Command+{N}"
windowInColumn = "Unassigned"
left = "Command+H"
down = "Command+J"
up = "Command+K"
right = "Command+L"
previous = "Unassigned"
downOrLeft = "Unassigned"
upOrRight = "Unassigned"
windowTop = "Unassigned"
windowBottom = "Unassigned"
windowDownOrTop = "Unassigned"
windowUpOrBottom = "Unassigned"
windowOrWorkspaceDown = "Unassigned"
windowOrWorkspaceUp = "Unassigned"
columnFirst = "Command+Home"
columnLast = "Command+End"
monitorNext = "Command+P"
monitorPrevious = "Unassigned"
monitorLast = "Unassigned"

[move]
columnToIndex = "Unassigned"
left = "Unassigned"
down = "Shift+Command+J"
up = "Shift+Command+K"
right = "Unassigned"
windowDown = "Unassigned"
windowUp = "Unassigned"
windowDownOrToWorkspaceDown = "Unassigned"
windowUpOrToWorkspaceUp = "Unassigned"
windowToWorkspaceUp = "Unassigned"
windowToWorkspaceDown = "Unassigned"
columnToWorkspaceUp = "Unassigned"
columnToWorkspaceDown = "Unassigned"
columnLeft = "Shift+Command+H"
columnRight = "Shift+Command+L"
columnToFirst = "Unassigned"
columnToLast = "Unassigned"
consumeOrExpelLeft = "Unassigned"
consumeOrExpelRight = "Unassigned"
consumeIntoColumn = "Command+Comma"
expelFromColumn = "Command+Period"
"windowToWorkspaceOnMonitor.1.down" = "Unassigned"
"windowToWorkspaceOnMonitor.1.left" = "Unassigned"
"windowToWorkspaceOnMonitor.1.right" = "Unassigned"
"windowToWorkspaceOnMonitor.1.up" = "Unassigned"
"windowToWorkspaceOnMonitor.2.down" = "Unassigned"
"windowToWorkspaceOnMonitor.2.left" = "Unassigned"
"windowToWorkspaceOnMonitor.2.right" = "Unassigned"
"windowToWorkspaceOnMonitor.2.up" = "Unassigned"
"windowToWorkspaceOnMonitor.3.down" = "Unassigned"
"windowToWorkspaceOnMonitor.3.left" = "Unassigned"
"windowToWorkspaceOnMonitor.3.right" = "Unassigned"
"windowToWorkspaceOnMonitor.3.up" = "Unassigned"
"windowToWorkspaceOnMonitor.4.down" = "Unassigned"
"windowToWorkspaceOnMonitor.4.left" = "Unassigned"
"windowToWorkspaceOnMonitor.4.right" = "Unassigned"
"windowToWorkspaceOnMonitor.4.up" = "Unassigned"
"windowToWorkspaceOnMonitor.5.down" = "Unassigned"
"windowToWorkspaceOnMonitor.5.left" = "Unassigned"
"windowToWorkspaceOnMonitor.5.right" = "Unassigned"
"windowToWorkspaceOnMonitor.5.up" = "Unassigned"
"windowToWorkspaceOnMonitor.6.down" = "Unassigned"
"windowToWorkspaceOnMonitor.6.left" = "Unassigned"
"windowToWorkspaceOnMonitor.6.right" = "Unassigned"
"windowToWorkspaceOnMonitor.6.up" = "Unassigned"
"windowToWorkspaceOnMonitor.7.down" = "Unassigned"
"windowToWorkspaceOnMonitor.7.left" = "Unassigned"
"windowToWorkspaceOnMonitor.7.right" = "Unassigned"
"windowToWorkspaceOnMonitor.7.up" = "Unassigned"
"windowToWorkspaceOnMonitor.8.down" = "Unassigned"
"windowToWorkspaceOnMonitor.8.left" = "Unassigned"
"windowToWorkspaceOnMonitor.8.right" = "Unassigned"
"windowToWorkspaceOnMonitor.8.up" = "Unassigned"
"windowToWorkspaceOnMonitor.9.down" = "Unassigned"
"windowToWorkspaceOnMonitor.9.left" = "Unassigned"
"windowToWorkspaceOnMonitor.9.right" = "Unassigned"
"windowToWorkspaceOnMonitor.9.up" = "Unassigned"

[layout]
toggleFullscreen = "Unassigned"
toggleNativeFullscreen = "Shift+Command+F"
toggleColumnTabbed = "Unassigned"
toggleColumnFullWidth = "Command+F"
expandColumnToAvailable = "Control+Option+Command+F"
cycleColumnWidthForward = "Unassigned"
cycleColumnWidthBackward = "Command+R"
cycleWindowWidthForward = "Unassigned"
cycleWindowWidthBackward = "Unassigned"
cycleWindowHeightForward = "Unassigned"
cycleWindowHeightBackward = "Unassigned"
decreaseColumnWidth = "Command+Minus"
increaseColumnWidth = "Command+Equal"
decreaseWindowWidth = "Unassigned"
increaseWindowWidth = "Unassigned"
decreaseWindowHeight = "Option+Shift+Command+Minus"
increaseWindowHeight = "Option+Shift+Command+Equal"
resetWindowHeight = "Control+Option+Command+R"
balanceSizes = "Shift+Command+B"
centerColumn = "Shift+Command+C"
centerVisibleColumns = "Unassigned"
toggleFocusedFloating = "Shift+Command+V"
assignScratchpad = "Shift+Command+Space"
toggleScratchpad = "Command+Space"
raiseAllFloating = "Unassigned"
rescueOffscreen = "Command+F12"

[debugging]
dumpRuntimeState = "Unassigned"
resetRuntimeState = "Unassigned"
restartClearingRuntimeState = "Unassigned"
toggleTraceCapture = "Control+Option+Command+T"

[ui]
commandPalette = "Shift+Command+M"
menuAnywhere = "Unassigned"
toggleOverview = "Command+O"
toggleWorkspaceBar = "Unassigned"
