
[appearance]
mode = "dark"

[borders]
enabled = false
width = 5.0

[borders.color]
alpha = 1.0
blue = 0.979300037944676
green = 1.0
red = 0.08458520228437894

[focus]
followsMouse = false
followsWindowToMonitor = false
moveMouseToFocusedWindow = false

[gaps]
size = 16.0

[gaps.outer]
bottom = 11.0
left = 11.0
right = 11.0
top = 11.0

[general]
animationsEnabled = true
hotkeysEnabled = true
ipcEnabled = false
preventSleepEnabled = false

[gestures]
fingerCount = 3
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0
scrollSnap = true

[mouseWarp]
axis = "horizontal"
margin = 1
monitorOrder = []

[niri]
alwaysCenterSingleColumn = true
centerFocusedColumn = "onOverflow"
columnWidthPresets = [0.3333333333333333, 0.5, 0.6666666666666666]
defaultColumnWidth = 0.33
infiniteLoop = false
maxVisibleColumns = 3
singleWindowAspectRatio = "16:9"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = false
enabled = true
height = 32.0
hideEmptyWorkspaces = false
labelFontSize = 16.0
notchAware = true
position = "overlappingMenuBar"
reserveLayoutSpace = false
showFloatingWindows = true
showLabels = true
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0
